const KEY_FOR_DECKS = "MOBILE_FLASH_CARDS";
const FETCH_DECKS = "FETCH_DECKS";
const CREATE_DECK = "CREATE_DECK";
const ADD_CARD_TO_DECK = "ADD_CARD_TO_DECK";
const REMOVE_DECK = "REMOVE_DECK";
const ANSWERED_CORRECTLY = "correct";
const ANSWERED_INCORRECTLY = "incorrect";
const KEY_FOR_NOTIFICATION = "notifications";

export { 
  KEY_FOR_DECKS, 
  FETCH_DECKS, 
  CREATE_DECK, 
  ADD_CARD_TO_DECK,
  REMOVE_DECK,
  ANSWERED_CORRECTLY,
  ANSWERED_INCORRECTLY,
  KEY_FOR_NOTIFICATION
};